name: DockerBuild

on: deployment

jobs:
  docker-build:
    name: Docker Build
    runs-on: [ self-hosted ]
    if: github.event.deployment.environment == 'docker'
    steps:
    - name: Pull
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.deployment.ref }}
    - name: Deployment Pending
      uses: deliverybot/deployment-status@v1
      with:
        state: pending
        token: ${{ github.token }}
    - name: Build
      run: |
        docker build -t ${{ github.sha }} .
    - name: Deployment Success
      if: success()
      uses: deliverybot/deployment-status@v1
      with:
        state: success
        token: ${{ github.token }}
    - name: Deployment Failure
      if: failure()
      uses: deliverybot/deployment-status@v1
      with:
        state: failure
        token: ${{ github.token }}

  terraform-apply:
    name: Terraform Apply
    runs-on: [ self-hosted ]
    container: hashicorp/terraform
    if: github.event.deployment.environment == 'terraform'
    steps:
    - name: Pull
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.deployment.ref }}
    - name: Deployment Pending
      uses: deliverybot/deployment-status@v1
      with:
        state: pending
        token: ${{ github.token }}
    - name: Apply
      run: |
        terraform apply -auto-approve
    - name: Deployment Success
      if: success()
      uses: deliverybot/deployment-status@v1
      with:
        state: success
        token: ${{ github.token }}
    - name: Deployment Failure
      if: failure()
      uses: deliverybot/deployment-status@v1
      with:
        state: failure
        token: ${{ github.token }}