name: DockerBuild

on: deployment

jobs:
  docker-build:
    name: Docker Build
    runs-on: [ self-hosted ]
    steps:
    - name: Pull
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.deployment.ref }}
    - name: Build
      run: |
        docker build -t ${{ github.sha }} .

